# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'
  demands:
  - msbuild
  - visualstudio

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: test
  condition: succeededOrFailed()

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: ShivDemo'
  inputs:
    deployToSlotOrASE: true
    SlotName: dev
    appType: webApp
    ConnectionType: AzureRM
    azureSubscription: 'Azure Microsoft Internal Subscription_shivshakti (0afb25ba-fe24-42fa-b79a-5452b082afc5)'
    ResourceGroupName: 'ShivDemo_group'
    WebAppName: ShivDemo
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
    #ExcludeFilesFromAppDataFlag: false
    #RemoveAdditionalFilesFlag: true